# Generated by Django 3.2 on 2022-01-10 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_produce'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='master_order',
        ),
    ]
